#!/usr/bin/env sh

curl --location 'https://bing.com/indexnow' \
--header 'Content-Type: application/json; charset=utf-8' \
--data '{
    "host": "zhonghongfly.com",
    "key": "a68538b2117d4f76ad7c5ee0d982d74c",
    "keyLocation": "https://zhonghongfly.com/a68538b2117d4f76ad7c5ee0d982d74c.txt",
    "urlList": [
        "https://zhonghongfly.com/categories/",
        "https://zhonghongfly.com/",
        "https://zhonghongfly.com/posts/",
        "https://zhonghongfly.com/tags/",
        "https://zhonghongfly.com/categories/%E7%BC%96%E7%A8%8B/",
        "https://zhonghongfly.com/design-pattern-behavioral-visitor/",
        "https://zhonghongfly.com/tags/%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F/",
        "https://zhonghongfly.com/design-pattern-behavioral-template-method/",
        "https://zhonghongfly.com/design-pattern-behavioral-strategy/",
        "https://zhonghongfly.com/design-pattern-behavioral-state/",
        "https://zhonghongfly.com/design-pattern-behavioral-observer/",
        "https://zhonghongfly.com/design-pattern-behavioral-memento/",
        "https://zhonghongfly.com/design-pattern-behavioral-mediator/",
        "https://zhonghongfly.com/design-pattern-behavioral-iterator/",
        "https://zhonghongfly.com/design-pattern-behavioral-interpreter/",
        "https://zhonghongfly.com/design-pattern-behavioral-command/",
        "https://zhonghongfly.com/design-pattern-behavioral-chain-of-responsibility/",
        "https://zhonghongfly.com/design-pattern-structural-proxy/",
        "https://zhonghongfly.com/design-pattern-structural-flyweight/",
        "https://zhonghongfly.com/design-pattern-structural-facade/",
        "https://zhonghongfly.com/design-pattern-structural-decorator/",
        "https://zhonghongfly.com/design-pattern-structural-composite/",
        "https://zhonghongfly.com/design-pattern-structural-bridge/",
        "https://zhonghongfly.com/design-pattern-structural-adapter/",
        "https://zhonghongfly.com/design-pattern-creation-prototype/",
        "https://zhonghongfly.com/design-pattern-creation-builder/",
        "https://zhonghongfly.com/design-pattern-creation-abstract-factory/",
        "https://zhonghongfly.com/design-pattern-creation-factory-method/",
        "https://zhonghongfly.com/design-pattern-creation-singleton/",
        "https://zhonghongfly.com/design-pattern-overview/",
        "https://zhonghongfly.com/about/",
        "https://zhonghongfly.com/en/categories/",
        "https://zhonghongfly.com/en/tags/design-pattern/",
        "https://zhonghongfly.com/en/",
        "https://zhonghongfly.com/en/posts/",
        "https://zhonghongfly.com/en/categories/programming/",
        "https://zhonghongfly.com/en/design-pattern-behavioral-visitor/",
        "https://zhonghongfly.com/en/tags/",
        "https://zhonghongfly.com/en/design-pattern-behavioral-template-method/",
        "https://zhonghongfly.com/en/design-pattern-behavioral-strategy/",
        "https://zhonghongfly.com/en/design-pattern-behavioral-state/",
        "https://zhonghongfly.com/en/design-pattern-behavioral-observer/",
        "https://zhonghongfly.com/en/design-pattern-behavioral-mediator/",
        "https://zhonghongfly.com/en/design-pattern-behavioral-memento/",
        "https://zhonghongfly.com/en/design-pattern-behavioral-iterator/",
        "https://zhonghongfly.com/en/design-pattern-behavioral-interpreter/",
        "https://zhonghongfly.com/en/design-pattern-behavioral-command/",
        "https://zhonghongfly.com/en/design-pattern-behavioral-chain-of-responsibility/",
        "https://zhonghongfly.com/en/design-pattern-structural-proxy/",
        "https://zhonghongfly.com/en/design-pattern-structural-flyweight/",
        "https://zhonghongfly.com/en/design-pattern-structural-facade/",
        "https://zhonghongfly.com/en/design-pattern-structural-decorator/",
        "https://zhonghongfly.com/en/design-pattern-structural-composite/",
        "https://zhonghongfly.com/en/design-pattern-structural-bridge/",
        "https://zhonghongfly.com/en/design-pattern-structural-adapter/",
        "https://zhonghongfly.com/en/design-pattern-creation-prototype/",
        "https://zhonghongfly.com/en/design-pattern-creation-builder/",
        "https://zhonghongfly.com/en/design-pattern-creation-abstract-factory/",
        "https://zhonghongfly.com/en/design-pattern-creation-factory-method/",
        "https://zhonghongfly.com/en/design-pattern-creation-singleton/",
        "https://zhonghongfly.com/en/design-pattern-overview/",
        "https://zhonghongfly.com/en/about/"
    ]
}'

echo "\\nBing IndexNow API request sent successfully."