baseURL = 'https://zhonghongfly.com/'
# 更改使用 Hugo 构建网站时使用的默认主题
theme = "LoveIt"
# 网站标题
title = "Hong Zhong's Blog"
# 设置默认的语言 ["en", "zh-cn", "fr", "pl", ...]
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写 ["en", "zh-CN", "fr", "pl", ...]
languageCode = "zh-CN"
# 语言名称 ["English", "简体中文", "Français", "Polski", ...]
languageName = "简体中文"
# 是否包括中日韩文字
hasCJKLanguage = true
# 版权描述，仅仅用于 SEO
copyright = "Copyright © 2019-present Hong Zhong, All rights reserved."
# 是否使用 robots.txt
enableRobotsTXT = false
# 是否使用 git 信息
enableGitInfo = true
# 是否使用 emoji 代码
enableEmoji = true
# 忽略一些构建错误
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]
# 分页配置
[pagination]
  disableAliases = false
  pagerSize = 20
  path = "page"
[params]
  # 网站默认主题样式 ["auto", "light", "dark"]
  defaultTheme = "auto"
  # 公共 git 仓库路径，仅在 enableGitInfo 设为 true 时有效
  gitRepo = ""
  # LoveIt 新增 | 0.1.1 哪种哈希函数用来 SRI, 为空时表示不使用 SRI
  # ["sha256", "sha384", "sha512", "md5"]
  fingerprint = ""
  # LoveIt 新增 | 0.2.0 日期格式
  dateFormat = "2006-01-02"
  # 网站图片, 用于 Open Graph 和 Twitter Cards
  images = ["/favicon.svg"]
  # 作者配置
  [params.author]
    name = "Hong Zhong"
    email = "zhonghongfly@foxmail.com"
    link = "https://zhonghongfly.com"
  # 作者的社交信息设置
  [params.social]
    GitHub = "zhonghongfly"
    Email = "zhonghongfly@foxmail.com"
    X = "zhonghongfly"
    RSS = true
  # LoveIt 新增 | 0.2.8 兼容性设置
  [params.compatibility]
    # 是否使用 Polyfill.io 来兼容旧式浏览器
    polyfill = false
    # 是否使用 object-fit-images 来兼容旧式浏览器
    objectFit = false
  # 文章页面全局配置
  [params.page]
    # LoveIt 新增 | 0.2.0 是否在主页隐藏一篇文章
    hiddenFromHomePage = false
    # LoveIt 新增 | 0.2.0 是否在搜索结果中隐藏一篇文章
    hiddenFromSearch = false
    # LoveIt 新增 | 0.2.0 是否使用 ruby 扩展语法
    ruby = true
    # LoveIt 新增 | 0.2.0 是否使用 fraction 扩展语法
    fraction = true
    # LoveIt 新增 | 0.2.0 是否使用 fontawesome 扩展语法
    fontawesome = true
    # 是否在文章页面显示原始 Markdown 文档链接
    linkToMarkdown = false
    # LoveIt 新增 | 0.2.4 是否在 RSS 中显示全文内容
    rssFullText = false
    [params.page.share]
      enable = false
    # LoveIt 新增 | 0.2.0 代码配置
    [params.page.code]
      # 是否显示代码块的复制按钮
      copy = true
      # 默认展开显示的代码行数
      maxShownLines = 100
      [params.page.code.render]
        goat = true
        mermaid = true
    # LoveIt 新增 | 0.2.0 目录配置
    [params.page.toc]
      # 是否使用目录
      enable = true
      # LoveIt 新增 | 0.2.9 是否保持使用文章前面的静态目录
      keepStatic = false
      # 是否使侧边目录自动折叠展开
      auto = true
  # LoveIt 新增 | 0.2.0 搜索配置
  [params.search]
    enable = true
    # 搜索引擎的类型 ["lunr", "algolia"]
    type = "algolia"
    # 文章内容最长索引长度
    contentLength = 4000
    # 搜索框的占位提示语
    placeholder = ""
    # LoveIt 新增 | 0.2.1 最大结果数目
    maxResultLength = 10
    # LoveIt 新增 | 0.2.3 结果内容片段长度
    snippetLength = 50
    # LoveIt 新增 | 0.2.1 搜索结果中高亮部分的 HTML 标签
    highlightTag = "em"
    # LoveIt 新增 | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
    absoluteURL = false
    [params.search.algolia]
      index = "Blog"
      appID = "C7YDR3U8EW"
      searchKey = "377783809718b1b538494735f04e9b74"
  # LoveIt 新增 | 0.2.0 Section (所有文章) 页面配置
  [params.section]
    # section 页面每页显示文章数量
    paginate = 20
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 10
  # LoveIt 新增 | 0.2.0 List (目录或标签) 页面配置
  [params.list]
    # list 页面每页显示文章数量
    paginate = 20
    # 日期格式 (月和日)
    dateFormat = "01-02"
    # RSS 文章数目
    rss = 10
  # LoveIt 新增 | 0.2.0 应用图标配置
  [params.app]
    # 当添加到 iOS 主屏幕或者 Android 启动器时的标题, 覆盖默认标题
    title = "Hong Zhong's Blog"
    # 是否隐藏网站图标资源链接
    noFavicon = false
    # 更现代的 SVG 网站图标, 可替代旧的 .png 和 .ico 文件
    svgFavicon = "/favicon.svg"
    # Android 浏览器主题色
    themeColor = "#ffffff"
    # Safari 图标颜色
    iconColor = "#5bbad5"
    # Windows v8-10磁贴颜色
    tileColor = "#da532c"
  # 网站分析配置
  [params.analytics]
    # Google Analytics
    [params.analytics.google]
      id = "G-2LF0CWMBT6"
      # 是否遵循浏览器的 “Do Not Track” 设置
      respectDoNotTrack = false
    # 百度统计
    [params.analytics.baidu]
      id = "cd01aea0ce1748b71c190f2d5679b998"
# Hugo 解析文档的配置
[markup]
  # 语法高亮设置
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    # false 是必要的设置
    # (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
  # Goldmark 是 Hugo 0.60 以来的默认 Markdown 解析库
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      # 是否在文档中直接使用 HTML 标签
      unsafe = true
  # 目录设置
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# 网站地图配置
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks 配置
[Permalinks]
  # posts = ":year/:month/:filename"
  posts = ":filename"

# 隐私信息配置
[privacy]
  # LoveIt 更改 | 0.3.1 Google Analytics 相关隐私设置 (也能在 params.analytics.google 配置)
  [privacy.googleAnalytics]
    # ...
  [privacy.twitter]
    # ...
  [privacy.youtube]
    # ...

# 用于输出 Markdown 格式文档的设置
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# 用于输出 Markdown 格式文档的设置
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# 用于 Hugo 输出文档的设置
[outputs]
  # LoveIt 更改 | 0.2.0
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

# Multilingual
# 多语言
[languages]
  [languages.en]
    weight = 2
    title = "Hong Zhong's Blog"
    languageCode = "en"
    languageName = "English"
    hasCJKLanguage = false
    copyright = "Copyright © 2019-present Hong Zhong, All rights reserved."
    # 菜单配置
    [languages.en.menu]
      [[languages.en.menu.main]]
        weight = 1
        identifier = "posts"
        pre = ""
        post = ""
        name = "Posts"
        url = "/posts/"
        title = ""
      [[languages.en.menu.main]]
        weight = 2
        identifier = "tags"
        pre = ""
        post = ""
        name = "Tags"
        url = "/tags/"
        title = ""
      [[languages.en.menu.main]]
        weight = 3
        identifier = "categories"
        pre = ""
        post = ""
        name = "Categories"
        url = "/categories/"
        title = ""
      [[languages.en.menu.main]]
        weight = 5
        identifier = "about"
        pre = ""
        post = ""
        name = "About"
        url = "/about/"
        title = ""
    [languages.en.params]
      # 网站标题, 用于 Open Graph 和 Twitter Cards
      title = "Hong Zhong's Blog"
      # 网站描述, 用于 RSS, SEO, Open Graph 和 Twitter Cards
      description = "This is a computer programming guide, including: Java basics, JDK source code, JVM, Spring, Spring Boot, Spring Cloud, database principles, MySQL, ElasticSearch, MongoDB, Docker, k8s, CI&CD, Linux, DevOps, distribution, middleware , development tools, Git, IDE, source code reading, reading notes, open source projects..."    
      # LoveIt 新增 | 0.2.0 页面头部导航栏标题配置
      [languages.en.params.header]
        # 桌面端导航栏模式 ["fixed", "normal", "auto"]
        desktopMode = "fixed"
        # 移动端导航栏模式 ["fixed", "normal", "auto"]
        mobileMode = "auto"
        [languages.en.params.header.title]
          # LOGO 的 URL
          logo = "/favicon.svg"
          # 标题名称
          name = "Hong Zhong's Blog"
          # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
          pre = ""
          # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
          post = ""
          # LoveIt 新增 | 0.2.5 是否为标题显示打字机动画
          typeit = false
      [languages.en.params.home]
        rss = 20
        [languages.en.params.home.profile]
          enable = true
          gravatarEmail = ""
          avatarURL = "/images/avatar.jpeg"
          subtitle = "The more efforts you make, the more fortune you get."
          typeit = true
          social = true
      # 页面底部信息配置
      [languages.en.params.footer]
        enable = true
        # LoveIt 新增 | 0.2.0 自定义内容 (支持 HTML 格式)
        custom = ''
        # LoveIt 新增 | 0.2.0 是否显示 Hugo 和主题信息
        hugo = false
        # LoveIt 新增 | 0.2.0 是否显示版权信息
        copyright = true
        # LoveIt 新增 | 0.2.0 是否显示作者
        author = true
        # 网站创立年份
        since = 2019
        # 许可协议信息 (支持 HTML 格式)
        license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
      
  [languages.zh-cn]
    weight = 1
    languageCode = "zh-CN"
    languageName = "简体中文"
    hasCJKLanguage = true
    copyright = "Copyright © 2019-present Hong Zhong, All rights reserved."
    # 菜单配置
    [languages.zh-cn.menu]
      [[languages.zh-cn.menu.main]]
        weight = 1
        identifier = "posts"
        pre = ""
        post = ""
        name = "所有文章"
        url = "/posts/"
        title = ""
      [[languages.zh-cn.menu.main]]
        weight = 2
        identifier = "tags"
        pre = ""
        post = ""
        name = "标签"
        url = "/tags/"
        title = ""
      [[languages.zh-cn.menu.main]]
        weight = 3
        identifier = "categories"
        pre = ""
        post = ""
        name = "分类"
        url = "/categories/"
        title = ""
      [[languages.zh-cn.menu.main]]
        weight = 5
        identifier = "about"
        pre = ""
        post = ""
        name = "关于"
        url = "/about/"
        title = ""
    [languages.zh-cn.params]
      # 网站标题, 用于 Open Graph 和 Twitter Cards
      title = "Hong Zhong's Blog"
      # 网站描述, 用于 RSS, SEO, Open Graph 和 Twitter Cards
      description = "这是一份计算机编程指南，包含: Java 基础, JDK源码, JVM, Spring, Spring Boot, Spring Cloud, 数据库原理, MySQL, ElasticSearch, MongoDB, Docker, k8s, CI&CD, Linux, DevOps, 分布式, 中间件, 开发工具, Git, IDE, 源码阅读，读书笔记, 开源项目..."
      # LoveIt 新增 | 0.2.0 页面头部导航栏标题配置
      [languages.zh-cn.params.header]
        # 桌面端导航栏模式 ["fixed", "normal", "auto"]
        desktopMode = "fixed"
        # 移动端导航栏模式 ["fixed", "normal", "auto"]
        mobileMode = "auto"
        [languages.zh-cn.params.header.title]
          # LOGO 的 URL
          logo = "/favicon.svg"
          # 标题名称
          name = "Hong Zhong's Blog"
          # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
          pre = ""
          # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
          post = ""
          # LoveIt 新增 | 0.2.5 是否为标题显示打字机动画
          typeit = false
      [languages.zh-cn.params.home]
        rss = 20
        [languages.zh-cn.params.home.profile]
          enable = true
          gravatarEmail = ""
          avatarURL = "/images/avatar.jpeg"
          subtitle = "越努力越幸运，坚守初心"
          typeit = true
          social = true
      # 页面底部信息配置
      [languages.zh-cn.params.footer]
        enable = true
        # LoveIt 新增 | 0.2.0 自定义内容 (支持 HTML 格式)
        custom = ''
        # LoveIt 新增 | 0.2.0 是否显示 Hugo 和主题信息
        hugo = false
        # LoveIt 新增 | 0.2.0 是否显示版权信息
        copyright = true
        # LoveIt 新增 | 0.2.0 是否显示作者
        author = true
        # 网站创立年份
        since = 2019
        # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
        icp = '<a href="http://beian.miit.gov.cn" target="_blank">赣ICP备18005347号-1</a>'
        # 许可协议信息 (支持 HTML 格式)
        license = '<a rel="license external nofollow noopener noreffer" href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank">CC BY-NC 4.0</a>'
      